FROM jenkins/jenkins:2.347-jdk11

USER jenkins
RUN jenkins-plugin-cli --latest false --plugins \
    blueocean:1.25.5 \
    build-timestamp:1.0.3 \
    timestamper:1.17 \
    pollscm:1.3.1 \
    github-api:1.303-400.v35c2d8258028

USER root
ENV FLUENTD_HOST=fluentd
ENV FLUENTD_PORT=24224
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV JENKINS_URL=http://jenkins:8080

COPY ./requirements.txt requirements.txt

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install -r requirements.txt && \
    rm -rf /var/lib/apt/lists/*

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy